### PR TITLE
Feature/update docstrings

### LINKED ISSUE #57: Update docstrings into desired format

### LINKED ISSUE #61: Update any references to literature using references.bib file

### PR DESCRIPTION
**Pull request by be904619**
### PR Type

Code style update

### Description

Existing docstrings for functions reformatted to use the style approved in the contributor guidelines. 

### Does this PR introduce a breaking change? 

 N/A

### Screenshots

(Write your answer here.)

### Checklist before requesting a review
- [X] I have made sure that my PR is not a duplicate.
- [X] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [X] I have performed a self-review of my code.
- [X] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by tl82649 — APPROVED** [review]
These all look good to me. I've made a few comments, but nothing that needs doing before merging.

**Review by ghost — COMMENTED** [review]
Thanks @be904619, you've done a thorough job and the documentation is very much better for it. Your work did show up a few style issues, for which I have created tickets #89, #99 and #100. Sorry for forgetting to create #89 sooner. The others are new but I want to get this right now.

**Review by ghost — CHANGES_REQUESTED** [review]
Thanks @be904619 . There are a few things that are not quite right yet. Sorry I missed the $ one on first review.

**Review by ghost — CHANGES_REQUESTED** [review]
In addition to a couple of overfull lines highlighted here, I think you've not seen some of my comments from my first review of kernel_herding.py. These are the unresolved conversations. Please could you go back and address them?

**Review by ghost — CHANGES_REQUESTED** [review]
@be904619 Only https://github.com/gchq/coreax/pull/88#discussion_r1310009057 needs fix, then we're done.

**Review by ghost — APPROVED** [review]
Thanks @be904619. That's a big branch complete.

**Pull request merged**
