### PR TITLE
fix: typo of 'coreset'

### PR DESCRIPTION
**Pull request by tc85324**
### PR Type

- Bugfix
- Documentation content changes

### Description
Fixes misspellings of 'coreset' as 'corset'

### Checklist before requesting a review
- [x] I have made sure that my PR is not a duplicate.
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have performed a self-review of my code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by tp832944** [comment]
@tc85324 I'm happy you're fixing this but am a little troubled by how this ended up on main when Pre-commit should have caught it. I feel like I should have seen a Pre-commit GitHub Action fail with this. Do you understand how it got through?

**Comment by tc85324** [comment]
Because 'corset' is a real word that looks very similar to 'coreset' it won't get caught by cspell and can be very easily missed by a reviewer. To avoid in the future, we can add 'corset' as a forbidden word in the cspell dictionary [see here](https://cspell.org/docs/forbidden-words/). @tp832944 I'm happy to add this to the PR  if you would like?

**Comment by tp832944** [comment]
> Because 'corset' is a real word that looks very similar to 'coreset' it won't get caught by cspell and can be very easily missed by a reviewer. To avoid in the future, we can add 'corset' as a forbidden word in the cspell dictionary [see here](https://cspell.org/docs/forbidden-words/). @tp832944 I'm happy to add this to the PR if you would like?

Ah yes, I had forgotten about the item of clothing. Given I can't see a use for `corset`, could you add it to the prohibited list please?

**Review by tp832944 — APPROVED** [review]

**Comment by tp832944** [comment]
@tc85324 I believe the failing check is now fixed on main. For some reason, rerunning the test isn't picking this up. Could you manually merge main into this branch please?

**Pull request merged**
